language: node_js
os: linux
dist: bionic
node_js:
  - 12
cache:
  npm: true
script:
  - npm install
  - npm run package
  - mv ./packaged/chrome.zip ./packaged/chrome-${TRAVIS_TAG}.zip;
  - mv ./packaged/firefox.zip ./packaged/firefox-${TRAVIS_TAG}.zip;
deploy:
  provider: releases
  token: $GITHUB_KEY
  skip_cleanup: true
  file:
    - ./packaged/chrome-${TRAVIS_TAG}.zip
    - ./packaged/firefox-${TRAVIS_TAG}.zip
  on:
    tags: true
