language: node_js
os: linux
dist: bionic
node_js:
  - lts
cache:
  npm: true
script:
  - npm run package
  - 'if [ "TRAVIS_TAG" != "" ]; mv ./packaged/chrome.zip ./packaged/chrome-${TRAVIS_TAG}.zip; fi'
  - 'if [ "TRAVIS_TAG" != "" ]; mv ./packaged/firefox.zip ./packaged/firefox-${TRAVIS_TAG}.zip; fi'
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file:
    - ./packaged/chrome-${TRAVIS_TAG}.zip
    - ./packaged/firefox-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
